version: '3.4'

services:
  cdshooks:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_HTTPS_PORT: 5001
      "ConnectionStrings__DefaultConnection": "Server=db;Database=CDSHooks;User ID=sa;Password=Pass@123;Connect Timeout=30;Trusted_Connection=False;MultipleActiveResultSets=true"
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  db:
    environment:
      - SA_PASSWORD=Pass@123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1434:1433"